name: Build Test
run-name: ${{ github.actor }} is operating the unity tests 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api #changing the script directory
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: yarn install #Dependencies install
      - run: yarn test #Unity tests
