name: BuildTest
run-name: ${{ BuildTest.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: yarn install
      - run: yarn test
