name: Publish Docker image
run-name: ${{ github.actor }} is trying to create and publish an image.

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        #uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        uses: docker/login-action@
        with:
          username: ${{ secrets.TP3_DOCKERUSERNAME }}
          password: ${{ secrets.TP3_DOCKERSECRET }}
      
#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        #uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#        uses: docker/metadata-action@v3
#        with:
#        # images: my-docker-hub-namespace/my-docker-hub-repository
#          images: zeezoutofficiel/tp3-github_actions

      - name: Build and push Docker image
        #uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        #uses: docker push zeezoutofficiel/tp3-github_actions:tagname
        #uses : docker push zeezoutofficiel/tp3-github_actions:tagname
        uses : docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}