name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    defaults:
      run: working-directory: ./api
    steps:
       - uses: actions/checkout@v3
       - name: Use Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '19'
           regisrty-url: https://registry.npmjs.org
       - cache: 'yarn'
       - run: npm install
       - run: npm run build --if-present
       - run: npm test
       - run: yarn install
       - run: yarn
       - run: yarn test


